"use client";

import React from 'react';
import { X, Printer, Sparkles } from 'lucide-react';

interface CheatsheetData {
  title: string;
  formulasAndRules: string[];
  coreDefinitions: { term: string; definition: string }[];
  quickTakeaways: string[];
}

interface CheatsheetModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: CheatsheetData | null;
}

export default function CheatsheetModal({ isOpen, onClose, data }: CheatsheetModalProps) {
  if (!isOpen || !data) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-4">
      {/* Modal Container */}
      <div className="bg-slate-950 border border-slate-800 rounded-2xl w-full max-w-3xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        
        {/* Header (Hidden on Print) */}
        <div className="p-4 border-b border-slate-800 flex items-center justify-between bg-slate-900/50 print:hidden">
          <div className="flex items-center space-x-2 text-cyan-400 font-semibold text-sm">
            <Sparkles className="w-4 h-4" />
            <span>Lumina Exam Cheatsheet</span>
          </div>
          <div className="flex items-center space-x-2">
            <button
              onClick={handlePrint}
              className="px-3 py-1.5 bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-400 border border-cyan-500/30 rounded-lg text-xs font-semibold flex items-center space-x-1.5 transition-all"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / Save PDF</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-white rounded-lg transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Printable Content Body */}
        <div className="p-6 overflow-y-auto space-y-6 text-slate-200 text-xs leading-relaxed print:p-0 print:text-black print:bg-white">
          
          <div className="border-b border-slate-800 pb-3 print:border-black">
            <h1 className="text-xl font-bold text-cyan-400 print:text-black uppercase tracking-wider">
              {data.title} — Quick Reference Sheet
            </h1>
            <p className="text-slate-400 print:text-slate-600 text-[11px]">Generated by Lumina AI for rapid review</p>
          </div>

          {/* Formulas / Key Rules */}
          {data.formulasAndRules?.length > 0 && (
            <div>
              <h2 className="text-sm font-bold text-pink-400 print:text-black mb-2 uppercase tracking-wide">
                ⚡ Core Formulas & Rules
              </h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                {data.formulasAndRules.map((item, idx) => (
                  <div key={idx} className="bg-slate-900/80 print:bg-slate-100 p-2.5 rounded-lg border border-slate-800 print:border-slate-300 font-mono text-[11px]">
                    {item}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Core Definitions */}
          {data.coreDefinitions?.length > 0 && (
            <div>
              <h2 className="text-sm font-bold text-cyan-400 print:text-black mb-2 uppercase tracking-wide">
                📚 Essential Definitions
              </h2>
              <div className="space-y-2">
                {data.coreDefinitions.map((def, idx) => (
                  <div key={idx} className="bg-slate-900/40 print:bg-slate-50 p-2.5 rounded-lg border border-slate-800/80 print:border-slate-200">
                    <span className="font-bold text-cyan-300 print:text-black">{def.term}: </span>
                    <span className="text-slate-300 print:text-slate-800">{def.definition}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Quick Exam Takeaways */}
          {data.quickTakeaways?.length > 0 && (
            <div>
              <h2 className="text-sm font-bold text-emerald-400 print:text-black mb-2 uppercase tracking-wide">
                🎯 Key Exam Takeaways
              </h2>
              <ul className="list-disc list-inside space-y-1 text-slate-300 print:text-slate-800">
                {data.quickTakeaways.map((tip, idx) => (
                  <li key={idx} className="bg-slate-900/20 print:bg-transparent p-1 rounded">{tip}</li>
                ))}
              </ul>
            </div>
          )}

        </div>
      </div>
    </div>
  );
}